# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JXFillSecurityCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JXFillSecurityCode

    pod 'Masonry'
  target 'JXFillSecurityCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JXFillSecurityCodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
